In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

print(a)
print(type(a))
print("shape:", a.shape)
print("dtype:", a.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
shape: (5,)
dtype: int64


In [3]:
## 数组创建方法
print(np.zeros((2, 3)))
print(np.ones((2, 3)))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [4]:
## 向量化计算
a = np.array([1, 2, 3, 4, 5])

print("a + 10 =", a + 10)
print("a * 2  =", a * 2)
print("a ** 2 =", a ** 2)

a + 10 = [11 12 13 14 15]
a * 2  = [ 2  4  6  8 10]
a ** 2 = [ 1  4  9 16 25]


In [ ]:
## 索引与切片
a = np.arange(10)

print("完整数组:", a)
print("第一个元素:", a[0])
print("前三个:", a[:3])
print("偶数位置:", a[::2])
print("大于 5:", a[a > 5])

完整数组: [0 1 2 3 4 5 6 7 8 9]
第一个元素: 0
前三个: [0 1 2]
偶数位置: [0 2 4 6 8]
大于 5: [6 7 8 9]


In [ ]:
## 二维数组与统计
m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("shape:", m.shape)
print("总和:", m.sum())
print("平均值:", m.mean())
print("按列求和:", m.sum(axis=0))
print("按行求和:", m.sum(axis=1))

shape: (2, 3)
总和: 21
平均值: 3.5
按列求和: [5 7 9]
按行求和: [ 6 15]


In [7]:
## 矩阵乘法
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A @ B)

[[19 22]
 [43 50]]
